[dependencies]
base = "https://github.com/dfinity/motoko-base#moc-0.7.4@d2f20b7a169cfabcf75c6672e24f016a6ed89f86"
array = "https://github.com/aviate-labs/array.mo#v0.2.0@863a668bcbb3c3799a62c36b2cba2c32d1fcc433"
StableTrieMap = "https://github.com/NatLabs/StableTrieMap#main@4781cb03efd34b124c22396c69710b374366c797"
StableBuffer = "https://github.com/canscale/StableBuffer#v0.2.0@1af0e8814bac5ca7ed23a6c094204b46d9056c2e"
itertools = "0.2.1"

[package]
name = "icrc1"
version = "0.0.1"
description = "A full implementation of the ICRC-1 fungible token standard"
repository = "https://github.com/NatLabs/icrc1"
keywords = [ "icrc1", "fungible", "token", "standard", "dfinity" ]
